/**
 * docs/VIDEO.md, generated: how the demo video was made, every number read from
 * the committed data, never typed in.
 *   data/video/voices.json        the voices, each line's session and check
 *   data/video/caller-gate.json   the live hearing gate for Q1-Q4
 *   data/video/takes.json         which take of each scene is used
 *   data/video/capture-*.json     each take's log, checks, sync and latency
 *   data/video/edl.json           the edit: shots, cuts, punch-ins
 *   data/video/final-checks.json  F2.7's checks on the rendered file
 *   docs/VOICE-SWEEP.md           the sweep's tool-call median
 *   data/e2e-audio-warm-on.json   the warm suite's median (scripts/warm-ab.ts)
 *
 *   node scripts/video/video-doc.ts
 */
import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { PROPER_NOUN_VARIANTS, VOICES } from './config.ts';
import { warmMedian } from './medians.ts';
import type { Edl } from './edl.ts';

const j = <T>(p: string): T => JSON.parse(readFileSync(p, 'utf8')) as T;
const ms = (v: number | null | undefined) => (v === null || v === undefined ? '-' : `${Math.round(v).toLocaleString('en-US')} ms`);
const s1 = (v: number) => `${(v / 1000).toFixed(1)} s`;

type Capture = {
  capture: string; scene: string; sessionId: string; lengthMs: number; frames: number; frameSize: string;
  sync: Array<{ label: string; offsetMs: number | null; ok: boolean }>;
  exchanges: Array<{ id: string; voiceToVoiceMs: number | null; heard: string | null }>;
  checks: Array<{ check: string; ok: boolean; detail: string }>;
  pageMicFidelity: Array<{ id: string; windows: number; bitExactWindows: number; slips: Array<{ atMs: number; samples: number }> }>;
  latency?: Array<{ id: string; clipTrailingSilenceMs: number; e2eStyleMs: number | null; playoutMs: number | null; videoMs: number | null; steps: { apiEndOfTurn: number | null; tools: Array<{ name: string; heldByGate?: boolean; toolCallAt: number | null; fetchMs: number | null; serverMs: number | null; networkMs: number | null; mcpMs: number | null; refine: string | null; refineMs: number | null; method: string | null; resultSentAt: number | null }>; lastToolResultSent: number | null; firstReplyAudioReceived: number | null; firstAudioPlayed: number | null } }>;
  log: Array<{ t: number; type: string; [k: string]: unknown }>;
};

export async function videoDoc(): Promise<string> {
  const voices = j<{ lines: Record<string, { voice: string; text: string; say?: string; checked: unknown; pass: boolean; note?: string; attempts: Array<{ sessionIds: string[]; ms: number; speechModel?: string | null; pass?: boolean; transcript?: string; firstDifference?: { expected: string; heard: string } }> }> }>('data/video/voices.json');
  const gate = j<{ runs: Array<{ scene: string; clips: Record<string, { voice: string; sha256: string }>; sessions: Array<{ sessionId: string; heard: Array<{ clip: string; exact: boolean; heard: string }> }>; verdicts: Record<string, string> }> }>('data/video/caller-gate.json');
  const takes = j<Record<string, string>>('data/video/takes.json');
  const edl = j<Edl>('data/video/edl.json');
  const final = existsSync('data/video/final-checks.json') ? j<{ file: string; sha256?: string; results: Array<{ check: string; ok: boolean; detail: string }>; silences: Array<{ start: number; end: number; what: string }>; transcript: { id: string; speechModel: string } }>('data/video/final-checks.json') : null;
  const sweep = readFileSync('docs/VOICE-SWEEP.md', 'utf8').match(/\| median voice-to-voice, turns that called a tool \| (\d+) ms \((\d+) turns\) \|/);
  if (!sweep) throw new Error('docs/VOICE-SWEEP.md has no tool-call median row');
  const warm = await warmMedian();
  const captureFiles = readdirSync('data/video').filter((f) => /^capture-.*\.json$/.test(f)).sort();
  const caps = new Map(captureFiles.map((f) => [f.replace(/^capture-|\.json$/g, ''), j<Capture>(`data/video/${f}`)]));
  const models = new Set(Object.values(voices.lines).flatMap((l) => l.attempts.map((a) => a.speechModel).filter(Boolean)));

  const md: string[] = [];
  md.push('# The demo video', '');
  md.push('Generated by `scripts/video/video-doc.ts` from `data/video/`; every number below is read from those files. Rebuild everything from the saved captures with one command (see the end).', '');

  md.push('## Voices', '');
  md.push('Every voice in the video is an AssemblyAI Voice Agent voice. Each line was made in its own session: the voice set in `output.voice`, the exact line in `greeting` (the greeting path speaks a line as written), and the greeting\'s `reply.audio` kept.', '');
  md.push('| role | voice |', '| --- | --- |', `| the agent (as interpres uses it) | \`${VOICES.agent}\` |`, `| the narrator | \`${VOICES.narrator}\` |`, `| the caller | \`${VOICES.caller}\` |`, '');
  md.push(`Narration is checked word for word with AssemblyAI's pre-recorded transcription (default model: ${[...models].join('; ')}), after case, punctuation and number format. Proper nouns may differ only as listed:`, '');
  for (const [w, alts] of Object.entries(PROPER_NOUN_VARIANTS)) md.push(`- **${w}**: ${alts.join(', ')}`);
  md.push('');
  md.push('| line | voice | length | session | check |', '| --- | --- | ---: | --- | --- |');
  for (const [id, l] of Object.entries(voices.lines).filter(([k]) => /^N\d+$/.test(k)).sort((a, b) => Number(a[0].slice(1)) - Number(b[0].slice(1)))) {
    const a = l.attempts.at(-1)!;
    const verdict = !l.pass ? 'FAIL' : a.pass ? `pass on try ${l.attempts.length}` : `pass on a re-check of try ${l.attempts.length}: ${l.note ?? ''}`;
    md.push(`| ${id} | ${l.voice} | ${ms(a.ms)} | \`${a.sessionIds.join('`, `')}\` | ${verdict} |`);
  }
  md.push('');
  md.push('Rewordings under the standing rule (a line that fails only because the transcriber spells a word differently): none were needed this round. Earlier, N10\'s "Every one answered out loud" was heard as "Everyone" on 4 of 4 tries; Sergiu changed it to "Each one answered out loud" (BUILDLOG, round F2).', '');

  md.push('## The caller', '');
  md.push('Caller clips are judged where they are heard: each streamed into a live Voice Agent session set up exactly as the page sets up that scene (the page\'s own `session.update`, compared with the public site\'s), passing when two sessions in a row hear it word for word (`scripts/video/caller-gate.ts`). The pre-recorded check is kept for them as information only.', '');
  md.push('| clip | voice | text | live gate | sessions |', '| --- | --- | --- | --- | --- |');
  for (const run of gate.runs) {
    for (const [id, c] of Object.entries(run.clips)) {
      const sess = run.sessions.map((s) => `\`${s.sessionId}\` ${s.heard.find((h) => h.clip === id)?.exact ? 'exact' : 'differs'}`).join(', ');
      md.push(`| ${id} | ${c.voice} | ${voices.lines[id]?.text ?? ''} | ${run.verdicts[id]} | ${sess} |`);
    }
  }
  const q5 = voices.lines.Q5!;
  md.push(`| Q5 | ${q5.voice} | ${q5.text} | not checked word for word | made in \`${q5.attempts.at(-1)!.sessionIds[0]}\` |`, '');

  md.push('## Scenes and takes', '');
  md.push(`A take counts only if every exchange passes its checks; the first such take of each scene is used (\`data/video/takes.json\`). Takes used: ${Object.entries(takes).map(([k, v]) => `${k} = \`${v}\``).join(', ')}.`, '');
  md.push('| take | scene | session | checks | used |', '| --- | --- | --- | --- | --- |');
  for (const [name, c] of caps) {
    const failed = c.checks.filter((x) => !x.ok);
    md.push(`| \`${name}\` | ${c.scene} | \`${c.sessionId}\` | ${failed.length === 0 ? 'all pass' : `FAIL: ${failed.map((x) => `${x.check} (${x.detail.slice(0, 60)})`).join('; ')}`} | ${Object.values(takes).includes(name) ? 'yes' : 'no'} |`);
  }
  md.push('');
  for (const [scene, name] of Object.entries(takes)) {
    const c = caps.get(name)!;
    const calls = c.log.filter((e) => e.type === 'ws.in' && e.msg === 'tool.call').map((e) => `\`${String(e.name)}(${JSON.stringify(e.arguments)})\``);
    md.push(`**Scene ${scene}** (\`${c.sessionId}\`): ${calls.join(', ') || 'no tool calls'}.`, '');
    for (const x of c.checks) md.push(`- ${x.ok ? 'ok' : 'FAIL'}: ${x.check}${x.detail ? ` (${x.detail.replace(/\|/g, '/').slice(0, 140)})` : ''}`);
    md.push('');
  }

  md.push('## Voice to voice, each exchange', '');
  md.push(`Next to the repo's two medians: the spoken sweep's median over the ${sweep[2]} turns that called a tool, **${Number(sweep[1]).toLocaleString('en-US')} ms** (\`docs/VOICE-SWEEP.md\`), and the warm spoken suite's **${Math.round(warm.medianMs).toLocaleString('en-US')} ms** over ${warm.turns} turns (\`scripts/warm-ab.ts\`). Never the sweep's 2.6 s, which covers every answer, tool or not.`, '');
  md.push('Both medians are measured the way `scripts/e2e-audio.ts` measures: from the moment the last chunk of the clip is sent to the moment the first `reply.audio` arrives. The video\'s figure is stricter at both ends: from the caller\'s last voiced sample (before the clip\'s own trailing silence) to the agent\'s first audible sample as the page played it (after the page\'s playback buffer). Both are shown.', '');
  md.push('| scene | exchange | video (last word to first sound) | e2e-audio style (clip end to first audio received) | clip\'s trailing silence | page playback buffer |', '| --- | --- | ---: | ---: | ---: | ---: |');
  for (const [scene, name] of Object.entries(takes)) {
    for (const l of caps.get(name)!.latency ?? []) md.push(`| ${scene} | ${l.id} | ${ms(l.videoMs)} | ${ms(l.e2eStyleMs)} | ${ms(l.clipTrailingSilenceMs)} | ${ms(l.playoutMs)} |`);
  }
  md.push('');
  md.push('### Where the time goes', '');
  md.push('Each step in ms after the caller\'s last word, from the take\'s log. A tool\'s page round trip is split into the network and the server\'s own time, with the MCP request and the Gateway refine inside it.', '');
  md.push('| exchange | API end of turn | tool calls | last result sent | first audio received | first audio played |', '| --- | ---: | --- | ---: | ---: | ---: |');
  for (const [scene, name] of Object.entries(takes)) {
    for (const l of caps.get(name)!.latency ?? []) {
      const tools = l.steps.tools.map((t) => t.heldByGate ? `${t.name} at ${t.toolCallAt} (held by the gate, no request)` : t.fetchMs === null ? `${t.name} at ${t.toolCallAt} (in the page)` : `${t.name} at ${t.toolCallAt}: ${t.fetchMs} ms${t.serverMs !== null ? ` = network ${t.networkMs} + server ${t.serverMs} (MCP ${t.mcpMs}, refine ${t.refine} ${t.refineMs} ms, ${t.method})` : ''}`).join('; ');
      md.push(`| ${scene} ${l.id} | ${l.steps.apiEndOfTurn ?? '-'} | ${tools || '-'} | ${l.steps.lastToolResultSent ?? '-'} | ${l.steps.firstReplyAudioReceived ?? '-'} | ${l.steps.firstAudioPlayed ?? '-'} |`);
    }
  }
  md.push('');

  md.push('## The edit', '');
  md.push(`${edl.shots.length} shots, ${(edl.durationMs / 1000).toFixed(1)} s. Scenes change with 300 ms crossfades. Every cut inside a scene is a visible 200 ms crossfade, and nothing between a caller's last word and the agent's first is ever cut, sped up or slowed down (\`scripts/video/edl.ts\` checks it for each exchange).`, '');
  md.push('| cut | at | removed from the take | reason |', '| --- | ---: | --- | --- |');
  for (const c of edl.cuts) md.push(`| ${c.shot} | ${s1(c.at)} | ${s1(c.fromMs)} to ${s1(c.toMs)} of the take | ${c.reason} |`);
  md.push('');
  md.push('| punch-in | at | on |', '| --- | ---: | --- |');
  for (const p of edl.punchIns) md.push(`| 1.4x, about 3 s | ${s1(p.start)} | ${p.reason} |`);
  md.push('');
  md.push('Captions: narration shows the script as written, timed by the narration clip\'s word timestamps. Caller lines show the live transcript (what interpres heard), with a spoken identifier printed in groups of four as the page\'s own gate card prints it. Agent lines come from AssemblyAI\'s transcript of the agent stem.', '');

  md.push('## Sync', '');
  md.push('Every capture starts (and, when the take ends cleanly, ends) with one white frame and a 20 ms beep at the same instant; the edit cuts both.', '');
  md.push('| take | flash to beep |', '| --- | --- |');
  for (const [, name] of Object.entries(takes)) md.push(`| \`${name}\` | ${caps.get(name)!.sync.map((x) => `${x.label} ${x.offsetMs} ms ${x.ok ? '(within a frame)' : '(OVER a frame)'}`).join(', ')} |`);
  md.push('');
  md.push('What the page\'s own microphone path received, against each clip as made, in 0.5 s windows:', '');
  md.push('| take | clip | bit-exact windows | sample slips |', '| --- | --- | ---: | --- |');
  for (const [, name] of Object.entries(takes)) for (const f of caps.get(name)!.pageMicFidelity) md.push(`| \`${name}\` | ${f.id} | ${f.bitExactWindows} of ${f.windows} | ${f.slips.length ? f.slips.map((x) => `${x.samples > 0 ? '+' : ''}${x.samples} at ${x.atMs} ms`).join(', ') : 'none'} |`);
  md.push('');

  if (final) {
    md.push('## The rendered file', '');
    md.push(`\`${final.file.split('/').at(-1)}\`${final.sha256 ? `, sha256 \`${final.sha256}\`` : ''}. The checks of brief F, F2.7 (\`scripts/video/checks.ts\`):`, '');
    for (const r of final.results) md.push(`- ${r.ok ? 'ok' : 'FAIL'}: ${r.check}: ${r.detail}`);
    md.push('', `Every silence of 2.5 s or more at -45 dB, and what it is:`, '');
    for (const x of final.silences) md.push(`- ${s1(x.start)} to ${s1(x.end)}: ${x.what}`);
    md.push('', `The transcript of the file's audio is AssemblyAI transcript \`${final.transcript.id}\` (${final.transcript.speechModel}, speaker labels on).`, '');
  }

  if (existsSync('data/video/after-capture.json')) {
    const after = j<{ what: string; changes: Array<{ where: string; before: string; after: string; why?: string }> }>('data/video/after-capture.json');
    md.push('## Changed on the page after capture', '');
    md.push(after.what, '');
    for (const c of after.changes) md.push(`- ${c.where}${c.why ? ` (${c.why})` : ''}: "${c.before}" is now "${c.after}"`);
    md.push('');
  }

  md.push('## Rebuild', '');
  md.push('From the saved captures in `video/captures/` (not in git: frames and stems are too heavy):', '');
  md.push('```', 'node --env-file=.env scripts/video/build.ts', '```', '');
  md.push('It makes the identifiers slide, the edit list, the render and the checks, then this page. Each step also runs alone: `identifiers-slide.ts`, `edl.ts`, `render.ts`, `checks.ts`, `video-doc.ts`. A new take is `capture.ts --scene A|B|C`, then `assemble.ts` and `transcribe.ts capture` on it.', '');
  return md.join('\n');
}

const isMain = process.argv[1] !== undefined && import.meta.url === `file://${process.argv[1]}`;
if (isMain) {
  writeFileSync('docs/VIDEO.md', `${await videoDoc()}\n`);
  console.log('written: docs/VIDEO.md');
}
