/**
 * Writes packages/core/src/english-10k.ts: the 10,000 most frequent English
 * words, for keeping them out of `input.keyterms`.
 *
 * Source: IlyaSemenov/wikipedia-word-frequency, word counts over the English
 * Wikipedia dump of 2023-04-13, pinned to one commit so the list can be rebuilt
 * byte for byte. MIT licence: see packages/core/THIRD_PARTY_LICENSES.md.
 *
 *   node scripts/common-words-build.ts
 */
import { writeFile } from 'node:fs/promises';

const COMMIT = '798ea9062d6e5aed1fa87deeeda1cd99d5b37903';
const URL = `https://raw.githubusercontent.com/IlyaSemenov/wikipedia-word-frequency/${COMMIT}/results/enwiki-2023-04-13.txt`;
const SIZE = 10_000;
const OUT = 'packages/core/src/english-10k.ts';

const res = await fetch(URL);
if (!res.ok) throw new Error(`${URL} -> ${res.status}`);
const words: string[] = [];
// One "word count" pair per line, most frequent first. Letters only, two or
// more of them: single letters are never keyterms anyway.
for (const line of (await res.text()).split('\n')) {
  const w = line.split(' ')[0] ?? '';
  if (/^[a-z]{2,}$/.test(w)) words.push(w);
  if (words.length === SIZE) break;
}
if (words.length !== SIZE) throw new Error(`only ${words.length} words`);

const lines: string[] = [];
for (let i = 0; i < words.length; i += 16) lines.push(words.slice(i, i + 16).join(' '));
await writeFile(OUT, `/**
 * The ${SIZE.toLocaleString('en-US')} most frequent letter-only English words, most frequent first,
 * counted over the English Wikipedia dump of 2023-04-13.
 *
 * Source: https://github.com/IlyaSemenov/wikipedia-word-frequency at commit
 * ${COMMIT}, results/enwiki-2023-04-13.txt.
 * MIT licence, Copyright (c) 2015 Ilya Semenov: packages/core/THIRD_PARTY_LICENSES.md.
 *
 * Generated by scripts/common-words-build.ts. Do not edit by hand.
 */
export const ENGLISH_10K = \`
${lines.join('\n')}
\`;
`);
console.log(`${OUT}: ${words.length} words, first "${words[0]}", last "${words[SIZE - 1]}"`);
